FROM ros:jazzy

RUN apt-get update && apt-get install -y \
    graphviz \
    libgraphviz-dev \
    pkg-config \
    python3-pip \
    libgl1 \
    libglib2.0-0 \
    libgl1-mesa-dri \
    libegl-mesa0 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --break-system-packages pygraphviz dear-ros-node-viewer

WORKDIR /ros_graph
