FROM ros:jazzy

RUN apt-get update && apt-get install -y \
    ros-jazzy-foxglove-bridge \
    && rm -rf /var/lib/apt/lists/*

CMD ["bash", "-c", "source /opt/ros/jazzy/setup.bash && ros2 launch foxglove_bridge foxglove_bridge_launch.xml"]
